disabled = false
languageCode = "Zh-cn"
languageName = "简体中文"
weight = 1
title = "misdazzling blog"

[params]
  displayName = "简体中文"
  isoCode = "Zh-cn"
  rtl = false
  dateFormat = "2 January 2006"
  # logo = "img/logo.png"
  # secondaryLogo = "img/secondary-logo.png"
  # description = "My awesome website"
  # copyright = "Copy, _right?_ :thinking_face:"
[params.author]
   name = "misdazzling"
   email = "misdaszzling01@gmail.com"
   image = "images/avatar.jpg"
   imageQuality = 96
   headline = "无限进步"
   bio = "无限进步"
   links = [
     { email = "mailto:misdazzling01@gmail.com" },
     { link = "https://link-to-some-website.com/" },
     { github = "https://github.com/misdazzling" },
     { gitlab = "https://gitlab.com/misdazzling" },  
     { heart = "https://afdian.com/a/dazzling/"}  
  ]
