name: Hugo Deploy GitHub Pages

on:
  push:
    branches:
      - source  # 设置为自己远程仓库的分支名

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: true
          fetch-depth: 0

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.124.1'  # 使用你的Hugo版本号
          extended: true # 如果你使用的不是extended版本的hugo，将true改为false

      - name: Build
        run: hugo --minify

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.HUGO_BLOG }}  # 使用你步骤6设置的Name(大写)
          publish_dir: ./public
          publish_branch: main  # 添加这一行, 可以将推送分支改为main
          user_name: 'github-actions[bot]'
          user_email: 'github-actions[bot]@users.noreply.github.com'
          commit_message: ${{ github.event.head_commit.message }}
          # cname: yourdomain.com  # 如果你有自定义域名, 替换为你的域名
